export enum ErrorCode {
  // Authentication & Authorization
  API_KEY_REQUIRED = 'API_KEY_REQUIRED',
  API_KEY_INVALID = 'API_KEY_INVALID',
  APP_INACTIVE = 'APP_INACTIVE',
  ADMIN_AUTH_REQUIRED = 'ADMIN_AUTH_REQUIRED',
  ADMIN_TOKEN_INVALID = 'ADMIN_TOKEN_INVALID',
  ADMIN_TOKEN_EXPIRED = 'ADMIN_TOKEN_EXPIRED',
  ADMIN_INSUFFICIENT_ROLE = 'ADMIN_INSUFFICIENT_ROLE',
  ADMIN_INACTIVE = 'ADMIN_INACTIVE',
  ADMIN_INVALID_CREDENTIALS = 'ADMIN_INVALID_CREDENTIALS',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  SOURCE_APP_REQUIRED = 'SOURCE_APP_REQUIRED',

  // Transactions
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  TRANSACTION_ALREADY_COMPLETED = 'TRANSACTION_ALREADY_COMPLETED',
  TRANSACTION_ALREADY_REFUNDED = 'TRANSACTION_ALREADY_REFUNDED',
  TRANSACTION_NOT_REFUNDABLE = 'TRANSACTION_NOT_REFUNDABLE',
  DUPLICATE_IDEMPOTENCY_KEY = 'DUPLICATE_IDEMPOTENCY_KEY',

  // Card
  CARD_DECLINED = 'CARD_DECLINED',
  CARD_TOKEN_NOT_FOUND = 'CARD_TOKEN_NOT_FOUND',
  CARD_TOKEN_INACTIVE = 'CARD_TOKEN_INACTIVE',
  LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',

  // Split
  SPLIT_AMOUNT_MISMATCH = 'SPLIT_AMOUNT_MISMATCH',
  SPLIT_ALREADY_EXISTS = 'SPLIT_ALREADY_EXISTS',

  // Provider
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
  PROVIDER_SWITCH_FAILED = 'PROVIDER_SWITCH_FAILED',

  // Webhook
  WEBHOOK_INVALID_SIGNATURE = 'WEBHOOK_INVALID_SIGNATURE',
  WEBHOOK_DUPLICATE_EVENT = 'WEBHOOK_DUPLICATE_EVENT',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // General
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
}
